### ISSUE TITLE
Mirror ocp-indent options

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#476]
Doc of `ocp-indent` options: https://github.com/OCamlPro/ocp-indent/blob/master/.ocp-indent

- [x] `base` (= `let-binding-indent`) #822
- [x] `type` (= `type-decl-indent`) #822
- [x] `in` (= `indent-after-in`) #822
- [x] `with` (= `function-indent`/`match-indent`) #853
- [x] `match_clause` (=  `cases-exp-indent`)
- [x] `ppx_stritem_ext` (= `stritem-extension-indent`) #840 
- [x] `max_indent` (= `max-indent`) #841 
- [x] `strict_with` (= `function-indent-nested`/`match-indent-nested`) #853
- [ ] `strict_else` :
    this option conflicts with `--if-then-else={compact|fit-or-vertical|keyword-first|k-r}`, we have the style of `strict_else=always` in each of the `if-then-else` cases. Would it really make sense to implement `strict_else={auto|never}` for these cases? I have the feeling the current options are more powerful than the ocp-indent option.
- [ ] `strict_comments`
- [ ] `align_ops`
    this option does not make sense for `ocamlformat` because if an expression breaks like this:
    ```ocaml
      let f x = x
        + y
    ```
    the first part of the expression (`x`) won't be on the same line as `let f x =` but will instead be in the same box as `+ y`, so neither `align_ops=true` nor `align_ops=false` are applicable for `ocamlformat`.
- [ ] `align_params`
    same issue as `align_ops`:
    ```ocaml
    match foo with
    | _ -> some_fun
      ^^parameter
    ```
