### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#568]
# Next minor release (0.9)

- [x] Less linebreaks for break-cases (PR #536)
- [x] Export ocamlformat_diff into another package (no `bos` dependency for ocamlformat)

# Medium-term

- [ ] Reducing the diff on `core_kernel` with `profile=janestreet` (issue #569)
  * [x] Less linebreaks for break-cases (PR #536)
  * [x] Non-doc comments in record definitions (PR #580)
  * [x] Extra space before doc comments in record definitions (PR #575)
  * [x] Missing break before closing bracket of polymorphic variants (PR #583)
- [ ] Replace `octavius` with `odoc` (issue #571)
- [ ] Format code blocks in docstrings (issue #478)

# Long-term

- [ ] Use a more appropriate AST
   * [ ] Enrich with comments
   * [ ] Sugarize
   * [ ] Easier to interact with Fmt boxes 
- [ ] Generate placeholder comments for  undocumented functions
- [ ] Expose an API (PR #589)
- [ ] Mirror ocp-indent options (issue #476)
- [ ] Use the merlin parser to not fail on syntactically invalid files

**Comment by IwanKaramazow** [comment]
Hi @gpetiot, can you elaborate what you mean by the section on "use a more appropiate AST"?
Enriching with comments, does this mean dumping comments in attributes and placing them on ast nodes? What does sugarize mean in this context? What do I need to imagine with `Easier to interact with Fmt boxes` ?

**Comment by gpetiot** [comment]
> Hi @gpetiot, can you elaborate what you mean by the section on "use a more appropiate AST"?
> Enriching with comments, does this mean dumping comments in attributes and placing them on ast nodes? What does sugarize mean in this context? What do I need to imagine with `Easier to interact with Fmt boxes` ?

Enriching the AST with comments would be nice in the long run but it is not where the complexity of Fmt_ast comes from and thus not our main motivation, our motivation is rather to have a more flexible way to handle boxes to allow a formatting that does not match the original shape of the AST (e.g. easier to have #207 or #462), see the issue #406.
In this context sugaring means transforming the AST in a form that is easier to process (e.g. transforming successive applications of the infix operator `::` into a list of elements, as an easier way to process OCaml lists).

**Comment by vphantom** [comment]
Just curious (hoping this roadmap is the right place to ask), seeing that both "0.9" objectives above have been met, is a release is imminent? We can't upgrade to Base v0.12 without sacrificing ocamlformat because its current (0.8) OPAM file states: `"base" {>= "v0.11.0" & < "v0.12"}`

**Comment by jberdine** [comment]
0.9 is imminent

**Comment by gpetiot** [comment]
See the milestones of the issues.
