### ISSUE TITLE
Bugs in opam repository

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#985]
Note that this experiment is based on https://github.com/ocaml-ppx/ocamlformat/pull/984

**How to reproduce**
```bash
mkdir all-sources
cd all-sources
opam list -a --columns name | grep -v "^#" | xargs -n 1 -I {} opam source {}
find ./ -type f -name "*.ml" -o -name "*.mli" | parallel -- ../ocamlformat/_build/release/src/ocamlformat.exe --enable-outside-detected-project --no-version-check --quiet --no-comment-check --ignore-invalid-option > /dev/null
```
gives, with some manual cleanup, the following errors:
- [x] `./bap-objdump.1.6.0/lib/x86_cpu/x86_types.ml: formatting did not stabilize after 10 iterations.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/998)
- [x] `./boomerang.1.1.0/lib/bakery.ml: ast changed.` (issue https://github.com/ocaml-ppx/ocamlformat/issues/994, fixed by https://github.com/ocaml-ppx/ocamlformat/pull/995)
- [x] `./frenetic.5.0.3/test/Test_Frenetic_NetKAT_Compiler.ml: ast changed.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/995)
- [x] `./mldonkey.3.1.6/src/daemon/common/commonMessages.ml: ast changed.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/995)
- [x] `./mldonkey.3.1.6/src/daemon/common/commonPictures.ml: ast changed.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/995)
- [ ] `./ocaml-variants.4.10.0+trunk+flambda/testsuite/tests/parsetree/source.ml: ~~generating invalid ocaml syntax~~ ast changed.` (~~fixed by https://github.com/ocaml-ppx/ocamlformat/pull/996~~)
- [x] `./ocaml_at_p.1.1.0/test/test.ml: ast changed.` (#987)
- [x] `./ppx_cstubs.0.2.0/examples/inline.c.ml: generating invalid ocaml syntax.` (#988)
- [x] `./ppx_monadic.2.3.0/tests/test_beginm.ml: unhandled exception. Use [--debug] for details.`
- [x] `./ppx_monoid.0.2/test/test.ml: unhandled exception. Use [--debug] for details.` (issue https://github.com/ocaml-ppx/ocamlformat/issues/990)
- [x] `./tensorflow.0.0.11/src/stubs/tf_bindings.ml: formatting did not stabilize after 10 iterations.`
- [ ] `./ott.0.29/src/lex_menhir_pp.ml: formatting did not stabilize after 10 iterations.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/921)
- [ ] `./ocamleditor.1.13.4/src/oebuild/oebuild_parallel.ml: formatting did not stabilize after 10 iterations.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/921)
- [x] `./ocaml-protoc.1.2.0/src/compilerlib/pb_codegen_backend.ml: formatting did not stabilize after 10 iterations.`
- [x] `./haxe.3.4.7/libs/ilib/ilMeta.mli: formatting did not stabilize after 10 iterations.` (issue https://github.com/ocaml-ppx/ocamlformat/issues/989)
- [ ] `./bsbnative.1.9.4/jscomp/core/js_main.ml: formatting did not stabilize after 10 iterations.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/921)
- [x] `./bsbnative.1.9.4/jscomp/test/ocaml_proto_test.ml: formatting did not stabilize after 10 iterations.`
- [x] `./frama-c-base.15.0/src/libraries/utils/utf8_logic.ml: formatting did not stabilize after 10 iterations.`
- [x] `./frama-c.19.0/src/libraries/utils/utf8_logic.ml: formatting did not stabilize after 10 iterations.`
- [ ] `./KaSim.4.0.0/KaSa_rep/lib/full/superargTk.ml: formatting did not stabilize after 10 iterations.` (fixed by https://github.com/ocaml-ppx/ocamlformat/pull/921)

(check the box then the issue has been identified and created or fixed)

**Comment by Julow** [comment]
I updated the list using the last release (0.13.0). Some are mysteriously fixed (not by fixing the linked issue) and one file has now a different bug (in `ocaml-variants`).
I didn't test on all opam, only on the files already in the list.

**Comment by hhugo** [comment]
What's the status here ? Is the list of issue up to date ?

**Comment by Julow** [comment]
I ran ocamlformat over 80% of all opam packages.

Error output:

```
ott.0.31/src/lex_menhir_pp.ml: formatting did not stabilize after 10 iterations.
cil.1.7.3/src/ext/optutil.ml: ast changed.
cil.1.7.3/src/ext/pta/olf.ml: ast changed.
cil.1.7.3/src/ext/pta/golf.ml: ast changed.
reason.3.6.0/formatTest/typeCheckedTests/input/comments.ml: ast changed.
why.2.41/src/hypotheses_filtering.ml: ast changed.
proverif.2.02pl1/src/display.ml: ast changed.
eliom.6.12.1/src/lib/server/eliommod_timeouts.ml: ast changed.
eliom.6.12.1/src/lib/server/eliommod_persess.ml: ast changed.
eliom.6.12.1/src/lib/server/eliommod_sersess.ml: ast changed.
eliom.6.12.1/src/lib/server/eliommod.ml: ast changed.
eliom.6.12.1/src/lib/server/eliommod_sessexpl.ml: ast changed.
eliom.6.12.1/src/lib/server/eliommod_datasess.ml: ast changed.
eliom.6.12.1/src/lib/server/eliommod_sessadmin.ml: ast changed.
lwt.5.3.0/src/unix/lwt_io.ml: ast changed.
lwt.5.3.0/test/core/test_lwt.ml: ast changed.
frama-c-base.15.0/src/plugins/pdg/ctrlDpds.ml: ast changed.
frama-c-base.15.0/src/kernel_services/ast_queries/logic_env.ml: ast changed.
kappa-binaries.4.1.0/core/cli/superargTk.tk.ml: formatting did not stabilize after 10 iterations.
odb-server.0.1/server.ml: ast changed.
pilat.1.3/src/lacaml_matrix.ml: ast changed.
memcad.1.0.0/c/c_pre_analyze.ml: ast changed.
rtop.3.6.0/formatTest/typeCheckedTests/input/comments.ml: ast changed.
links-sqlite3.0.9.1/core/types.ml: ast changed.
lwt_camlp4.1.0.0/test/core/test_lwt.ml: ast changed.
gxl-light.1.0/GXL.ml: ast changed.
beluga.0.8.2/src/core/synext.ml: ast changed.
beluga.0.8.2/src/core/synint.ml: ast changed.
kappa-library.4.1.0/core/cli/superargTk.tk.ml: formatting did not stabilize after 10 iterations.
flowtype.0.94.0/src/typing/repos_cache.ml: ast changed.
color-brewery.0.1/src/color_brewery.ml: ast changed.
pvem.0.0.1/pvem.ml: ast changed.
haxe.4.1.1/src/codegen/gencommon/castDetect.ml: ast changed.
ocaml-secondary-compiler.4.08.1-1/testsuite/tests/parsetree/source.ml: ast changed.
ocaml-secondary-compiler.4.08.1-1/testsuite/tests/typing-poly/poly.ml: generating invalid ocaml syntax.
ocaml-secondary-compiler.4.08.1-1/testsuite/tests/typing-gadts/didier.ml: ast changed.
ocamlformat.0.15.0/test/passing/sequence.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/comments_args.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/comments.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/break_cases.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/loc_stack.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/extensions.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/label_option_default_args.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/wrap_comments.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/module_item_spacing.mli: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/source.ml: formatting did not stabilize after 2 iterations.
ocamlformat.0.15.0/test/passing/js_source.ml: formatting did not stabilize after 2 iterations.
links-postgresql.0.9.1/core/types.ml: ast changed.
bisect_ppx-ocamlbuild.1.0.1/src/ppx/instrument.ml: ast changed.
bisect_ppx-ocamlbuild.1.0.1/test/unit/fixtures/exclude-comments/excluded_clauses.reference.ml: ast changed.
bisect_ppx-ocamlbuild.1.0.1/test/unit/fixtures/ppx-integration/attributes.ml: ast changed.
bisect_ppx-ocamlbuild.1.0.1/test/unit/fixtures/ppx-integration/attributes.reference.ml: ast changed.
bisect_ppx-ocamlbuild.1.0.1/test/unit/fixtures/instrument/expr_match.reference.ml: ast changed.
bisect_ppx-ocamlbuild.1.0.1/test/unit/fixtures/instrument/expr_match_ppat_open_404.reference.ml: ast changed.
frama-c.21.1/src/plugins/pdg/ctrlDpds.ml: ast changed.
frama-c.21.1/src/kernel_services/ast_queries/logic_env.ml: ast changed.
batteries.3.1.0/src/batLazyList.ml: ast changed.
batteries.3.1.0/battop.ml: ast changed.
ocaml-data-notation.0.0.11/test/data/oasis-examples/PropList.ml: ast changed.
zephyrus.0.1/src/datatypes/data_model.ml: ast changed.
goblint-cil.1.7.4/src/ext/pta/olf.ml: ast changed.
goblint-cil.1.7.4/src/ext/pta/golf.ml: ast changed.
links.0.9.1/core/types.ml: ast changed.
opa-base.1.1.0+4263/ocamllib/libbase/traverseInterface.ml: ast changed.
opa-base.1.1.0+4263/compiler/libqmlcompil/qmlTypes.ml: ast changed.
opa-base.1.1.0+4263/compiler/libbsl/bslPluginInterface.ml: ast changed.
opa-base.1.1.0+4263/compiler/opa/pass_FunActionJsCallGeneration.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/ppx-integration/attributes.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/ppx-integration/attributes.reference.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/instrument/cases.reference.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/instrument/function.reference.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/instrument/match.reference.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/instrument/try.reference.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/instrument/ppat_open_404.reference.ml: ast changed.
bisect_ppx.2.4.1/test/unit/fixtures/instrument/match_408.reference.ml: ast changed.
bsbnative.1.9.4/jscomp/core/lam_compile.ml: ast changed.
bsbnative.1.9.4/jscomp/core/lam_coercion.ml: ast changed.
bsbnative.1.9.4/jscomp/core/js_main.ml: formatting did not stabilize after 10 iterations.
bsbnative.1.9.4/jscomp/core/lam_pass_deep_flatten.ml: ast changed.
bsbnative.1.9.4/jscomp/core/lam.ml: ast changed.
bsbnative.1.9.4/jscomp/test/for_side_effect_test.ml: ast changed.
bsbnative.1.9.4/jscomp/test/mutable_obj_test.ml: generating invalid ocaml syntax.
bsbnative.1.9.4/jscomp/test/test_bs_this.ml: generating invalid ocaml syntax.
bsbnative.1.9.4/jscomp/test/mario_game.ml: generating invalid ocaml syntax.
bsbnative.1.9.4/jscomp/runtime/js_internal.ml: ast changed.
bsbnative.1.9.4/jscomp/others/js_array.ml: ast changed.
bsbnative.1.9.4/vendor/ocaml/testsuite/tests/typing-poly/poly.ml: generating invalid ocaml syntax.
bsbnative.1.9.4/vendor/ocaml/testsuite/tests/typing-gadts/didier.ml: ast changed.
archsat.1.1/src/core/dispatcher.ml: ast changed.
ocaml-src.4.11.1/testsuite/tests/parsetree/source.ml: ast changed.
ocaml-src.4.11.1/testsuite/tests/typing-poly/poly.ml: generating invalid ocaml syntax.
ocaml-src.4.11.1/testsuite/tests/typing-gadts/didier.ml: ast changed.
lwt_ppx.2.0.1/src/unix/lwt_io.ml: ast changed.
lwt_ppx.2.0.1/test/core/test_lwt.ml: ast changed.
kappa-server.4.1.0/core/cli/superargTk.tk.ml: formatting did not stabilize after 10 iterations.
mirage-qubes.0.8.3/lib/formats.ml: ast changed.
bap-saluki.bap-1.6/minos/checks/system_simple_check.ml: ast changed.
bap-saluki.bap-1.6/minos/checks/system_check.ml: ast changed.
bap-saluki.bap-1.6/minos/summary.ml: ast changed.
bap-saluki.bap-1.6/minos/interprocedural.ml: ast changed.
bap-saluki.bap-1.6/minos/util.ml: ast changed.
relit-reason.0.0.2/formatTest/typeCheckedTests/input/comments.ml: ast changed.
kappa-agents.4.1.0/core/cli/superargTk.tk.ml: formatting did not stabilize after 10 iterations.
lwt_react.1.1.3/src/unix/lwt_io.ml: ast changed.
lwt_react.1.1.3/test/core/test_lwt.ml: ast changed.
ocaml-variants.4.12.0+trunk+no-flat-float-array/testsuite/tests/parsetree/source.ml: ast changed.
ocaml-variants.4.12.0+trunk+no-flat-float-array/testsuite/tests/typing-poly/poly.ml: generating invalid ocaml syntax.
ocaml-variants.4.12.0+trunk+no-flat-float-array/testsuite/tests/typing-gadts/didier.ml: ast changed.
```

On some files, OCamlformat is stuck (taking 100% of the CPU for ever):
  * dot-merlin-reader.3.4.0/src/ocaml/typing/407_0/predef.ml
  * proverif.2.02pl1/src/rules.ml
  * camlp5.8.00~alpha04/ocaml_src/meta/q_MLast.ml
  * merlin.3.4.0/src/ocaml/typing/409/predef.ml
  * earley-ocaml.1.1.0/bootstrap/4.04.2/pa_ocaml.ml
  * bsbnative.1.9.4/jscomp/test/ocaml_typedtree_test.ml

These projects contain many files that trigger this problem.

**Comment by hhugo** [comment]
I'm surprised by the amount of "ast changed" in the report above. I wonder if we've introduced regressions since the initial report.

**Comment by hhugo** [comment]
Has anyone looked at this since my last comment ?

**Comment by gpetiot** [comment]
I'm running the script to see if the results improved since last time and will open issues for cases to fix.

**Comment by hhugo** [comment]
What's the status of this ? Are there still bugs found while parsing opam files ?

**Comment by Julow** [comment]
I am not aware of any related fixes or new bugs. It would be nice to re-run the survey.

**Comment by hhugo** [comment]
## BUG: ast changed.
many related to #2405

"./frenetic.5.0.5/src/lib/netkat/FabricGen.ml".
"./alt-ergo-lib-free.2.3.3.dune3/lib/reasoners/satml.ml".
"./alt-ergo-lib-free.2.3.3.dune3/lib/reasoners/intervalCalculus.ml".
"./alt-ergo-lib.2.4.3/src/lib/reasoners/satml.ml".
"./alt-ergo-lib.2.4.3/src/lib/reasoners/intervalCalculus.ml".
"./decimal.0.4.0/test/json.ml".
"./orsetto.1.1.3/src/cbor/cbor_decode.ml".
"./orsetto.1.1.3/src/cf/cf_annot.ml".
"./alt-ergo.2.4.3/src/lib/reasoners/satml.ml".
"./alt-ergo.2.4.3/src/lib/reasoners/intervalCalculus.ml".
"./alt-ergo-free.2.3.3.dune3/lib/reasoners/satml.ml".
"./alt-ergo-free.2.3.3.dune3/lib/reasoners/intervalCalculus.ml".
"./alt-ergo-parsers-free.2.3.3.dune3/lib/reasoners/satml.ml".
"./alt-ergo-parsers-free.2.3.3.dune3/lib/reasoners/intervalCalculus.ml".
"./altgr-ergo.2.4.3/src/lib/reasoners/satml.ml".
"./altgr-ergo.2.4.3/src/lib/reasoners/intervalCalculus.ml".

## BUG: comment changed.

many related to the left margin 

"./daypack-lib.0.0.6/tests/sched.ml".
"./ocamlspot.4.07.0.2.3.2/tests/object.ml".
"./bare_encoding.0.3/tests/example2_standalone.ml".
"./batteries.3.6.0/src/batBase64.ml".
"./batteries.3.6.0/src/batBool.ml".
"./batteries.3.6.0/src/batFingerTree.ml".
"./batteries.3.6.0/src/batRef.ml".
"./batteries.3.6.0/src/batComplex.ml".
"./batteries.3.6.0/src/batRMutex.ml".
"./batteries.3.6.0/src/batISet.ml".
"./batteries.3.6.0/src/batUref.ml".
"./batteries.3.6.0/src/batGc.ml".
"./batteries.3.6.0/src/batCache.ml".
"./batteries.3.6.0/src/batDeque.ml".

## BUG: generating invalid ocaml syntax.

both covered by #2406 

"./eliom.10.0.0/src/lib/eliom_lib.client.ml"
"./ocsigen-start.6.1.0/tools/sort_deps.ml"

## BUG: generating invalid comment attachement

#2407, ...

"./nloge.0.0.2/src/emit.ml"
"./hack_parallel.1.0.1/scripts/gen_build_id.ml"
"./shcaml.0.2.1/examples/downsample.ml"
"./vg.0.9.4/db/colors.ml"
"./vg.0.9.4/db/escapes.ml"
"./vg.0.9.4/db/alphas.ml"
"./vg.0.9.4/db/gradients.ml"
"./vg.0.9.4/db/arrowhead.ml"
"./odb-server.0.1/server.ml"
"./vg.0.9.4/db/doc.ml"
"./vg.0.9.4/db/paths.ml"
"./flowtype.0.94.0/scripts/gen_build_id.ml"
"./ocaml-data-notation.0.0.11/test/data/oasis-examples/PropList.ml"
"./batteries.3.6.0/toplevel/battop.ml"
"./ocamlbuild.0.14.2+win/src/ocaml_specific.ml"
"./rmlbuild.0.14.0-00/src/ocaml_specific.ml"
"./ocamleditor.1.13.4/build.ml"

**Comment by hhugo** [comment]
I've filtered out all errors related to `formatting did not stabilize after 10 iterations`

**Comment by Julow** [comment]
Thanks a lot for this !

**Comment by hhugo** [comment]
We're making progress, trying to format a large part of opam-repository I only see issues related to stabilization. (the the one mentioned in #2405)

I'm tempted to close this issue and open a new one that would only track stabilization issues (we already have some #2454)  
Here is the list of files failing to stabilize:
```
bddapron.2.3.3/bdd/cond.mli
bddapron.2.3.3/bdd/cond.ml
dolmen_type.0.9/src/model/bitv.ml
stog_server.0.20.0/lib/tmap.mli
bitvec-sexp.2.5.0/lib/bap_c/bap_c_abi.mli
bare.2.5.0/lib/bap_c/bap_c_abi.mli
plasma.0.6.2/src/pfs_namenode/nn_alloc_balanced.ml
plasma.0.6.2/src/pfs_namenode/nn_elect.ml
plasma.0.6.2/src/pfs_namenode/nn_blockmap.ml
plasma.0.6.2/src/pfs_namenode/nn_commit.ml
plasma.0.6.2/src/pfs_namenode/nn_monitor.ml
plasma.0.6.2/src/plasmaclient/plasma_inodecache.ml
plasma.0.6.2/src/pfs_namenode/nn_state.ml
plasma.0.6.2/src/pfs_namenode/nn_db.ml
plasma.0.6.2/src/plasmasupport/plasma_util.ml
plasma.0.6.2/src/pfs_namenode/nn_coord.ml
plasma.0.6.2/src/mr_framework/mapred_sched1.ml
plasma.0.6.2/src/pfs_datanode/dn_manager.ml
plasma.0.6.2/src/pfs_nfs3/nfs3d_manager.ml
plasma.0.6.2/src/plasmaclient/plasma_client.ml
plasma.0.6.2/src/mr_framework/mapred_sched.ml
obrowser.1.1.1/axo/AXOHtml.ml
obrowser.1.1.1/axo/AXOWidgets.ml
plasma.0.6.2/src/mr_framework/mapred_io.ml
libzipperposition.2.1/src/demo/resolution/resolution1.ml
libzipperposition.2.1/src/core/Unif_intf.ml
kind2.2.0.0/src/model.ml
pacomb.1.1/lib/comb.ml
capnp.3.5.0/src/runtime/structPointer.ml
capnp.3.5.0/src/runtime/listPointer.ml
ocamlbuild.0.14.2+win/src/ocaml_specific.ml
tezt-tezos.17.1/src/lib_epoxy_tx/tx_rollup.ml
ppx_netblob.1.2.1/src/ppx_netblob.ml
gopcaml-mode.0.0.6/gopcaml_state.ml
lablgtk3-sourceview3.3.1.3/src/glib.mli
bitvec.2.5.0/lib/bap_c/bap_c_abi.mli
shcaml.0.2.1/examples/downsample.ml
shcaml.0.2.1/doc/tutorial.ml
coccinelle.1.1.1/bundles/menhirLib/menhir-20181113/src/LRijkstra.ml
monads.2.5.0/lib/bap_c/bap_c_abi.mli
ocaml-http.0.1.6/examples/threads.ml
stog_extern.0.20.0/lib/tmap.mli
logtk.2.1/src/demo/resolution/resolution1.ml
logtk.2.1/src/core/Unif_intf.ml
stog_rel_href.0.20.0/lib/tmap.mli
dolmen_loop.0.9/src/model/bitv.ml
goblint.2.1.0/src/solvers/td3.ml
goblint.2.1.0/src/analyses/base.ml
bitvec-order.2.5.0/lib/bap_c/bap_c_abi.mli
stog_noexec.0.20.0/lib/tmap.mli
stog_sitemap.0.20.0/lib/tmap.mli
stog_multi_doc.0.20.0/lib/tmap.mli
lablgtk3-gtkspell3.3.1.3/src/glib.mli
cordova-plugin-fcm.1.0/cordova_fcm.mli
simple-bmc.0.0.1/src/type.ml
menhirLib.20230608/src/LRijkstraClassic.ml
menhirLib.20230608/src/LRijkstraFast.ml
ocaml-variants.5.2.0+trunk/testsuite/tests/weak-ephe-final/weaklifetime2.ml
ocaml-variants.5.2.0+trunk/testsuite/tests/backtrace/backtrace2.ml
alba.0.4.4/ocaml/alba1/signature.ml
alba.0.4.4/ocaml/alba1/term_table.ml
alba.0.4.4/ocaml/alba1/context.ml
alba.0.4.4/ocaml/alba1/class_table.ml
alba.0.4.4/ocaml/alba1/term.ml
alba.0.4.4/ocaml/alba1/proof_context.ml
lem.2022-12-10/src/typed_ast.ml
gtk-light.0.0.1/myocamlbuild.ml
coq-core.8.17.1/kernel/cooking.ml
coq-core.8.17.1/kernel/indtypes.ml
coq-core.8.17.1/kernel/reduction.ml
coq-core.8.17.1/kernel/cClosure.ml
stog_dot.0.20.0/lib/tmap.mli
stog_rdf.0.20.0/lib/tmap.mli
regular.2.5.0/lib/bap_c/bap_c_abi.mli
stog_markdown.0.20.0/lib/tmap.mli
ocaml-src.5.0.dev/testsuite/tests/weak-ephe-final/weaklifetime2.ml
ocaml-src.5.0.dev/testsuite/tests/backtrace/backtrace2.ml
stk_iconv.0.1.0/lib/textbuffer.ml
coq-stdlib.8.17.1/kernel/cooking.ml
coq-stdlib.8.17.1/kernel/indtypes.ml
coq-stdlib.8.17.1/kernel/reduction.ml
coq-stdlib.8.17.1/kernel/cClosure.ml
ocamlfind-secondary.1.9.6/src/findlib/fl_lint.ml
rmlbuild.0.14.0-00/src/ocaml_specific.ml
bitvec-binprot.2.5.0/lib/bap_c/bap_c_abi.mli
jenga.v0.11.0/lib/api.mli
vg.0.9.4/db/arrowhead.ml
vg.0.9.4/db/illusions.ml
ocamlspot.4.07.0.2.3.2/tests/test.ml
ocamlspot.4.07.0.2.3.2/tests/functor_call.ml
SZXX.3.0.1/src/xml.mli
why.2.41/jc/jc_typing.ml
why.2.41/src/encoding_mono.ml
why.2.41/src/encoding_mono_inst.ml
why.2.41/jc/jc_interp.ml
why.2.41/src/smtlib.ml
why.2.41/src/encoding_mono2.ml
why.2.41/src/theoryreducer.ml
why.2.41/src/z3.ml
dolmen_bin.0.9/src/model/bitv.ml
coq.8.17.1/kernel/cooking.ml
coq.8.17.1/kernel/indtypes.ml
coq.8.17.1/kernel/reduction.ml
coq.8.17.1/kernel/cClosure.ml
ocsfml.2.0/OcsfmlWindow/ocsfmlWindow.mli
dolmen.0.9/src/model/bitv.ml
opam-lib.1.3.1/src/core/opamProcess.mli
opam-lib.1.3.1/src/format/opamTypes.mli
lwt_named_threads.0.1/lib/lwt_mark.ml
spdiff.0.1/localcocci/parsing_cocci/comm_assoc.ml
ocp_reveal.0.1/src/reveal.ml
spdiff.0.1/localcocci/parsing_cocci/iso_pattern.ml
stog_all.0.20.0/lib/tmap.mli
menhir.20230608/src/LRijkstraClassic.ml
menhir.20230608/src/LRijkstraFast.ml
planck.2.2.0/test/expr.ml
stog.0.20.0/lib/tmap.mli
ogre.2.5.0/lib/bap_c/bap_c_abi.mli
ppx_deriving_qcheck.0.4.0/src/core/QCheck.mli
qcheck-ounit.0.21.1/src/core/QCheck.mli
stog_plugins.0.20.0/lib/tmap.mli
advi.2.0.0/src/rc.mli
merlin-extend.0.6.1/extend_protocol.ml
ocaml-base-compiler.5.1.0~beta1/testsuite/tests/weak-ephe-final/weaklifetime2.ml
ocaml-base-compiler.5.1.0~beta1/testsuite/tests/backtrace/backtrace2.ml
nit.0.6/argE.ml
extprot.1.7.0/runtime/limits.mli
not-ocamlfind.0.10/local-packages/ocamlfind/src/findlib/fl_lint.ml
ketrew.3.2.1/src/lib/engine.ml
yurt.0.6/example/example.ml
coqide-server.8.17.1/kernel/cooking.ml
coqide-server.8.17.1/kernel/indtypes.ml
coqide-server.8.17.1/kernel/reduction.ml
coqide-server.8.17.1/kernel/cClosure.ml
graphlib.2.5.0/lib/bap_c/bap_c_abi.mli
alphaCaml.20061214/tool/kind.ml
ocaml-secondary-compiler.4.08.1-1/testsuite/tests/misc/weaklifetime2.ml
ocaml-secondary-compiler.4.08.1-1/testsuite/tests/backtrace/backtrace2.ml
stog_asy.0.20.0/lib/tmap.mli
ocaml-webworker.0.0.1/ocaml_webworker/merlin_lite/src/extend/extend_protocol.ml
qcheck-alcotest.0.21.1/src/core/QCheck.mli
squirrel.0.1/src/reduction.ml
squirrel.0.1/src/equiv.ml
ocaml-gist.0.0.1/ocaml_webworker/merlin_lite/src/extend/extend_protocol.ml
tezt-performance-regression.17.1/src/lib_epoxy_tx/tx_rollup.ml
camlp4.4.14+1/camlp4/boot/camlp4boot.ml
0install-solver.2.18/src/tests/test_sat.ml
dolmen_lsp.0.9/src/model/bitv.ml
ocamlfind.1.9.6/src/findlib/fl_lint.ml
stog_writing.0.20.0/lib/tmap.mli
lablgtk3.3.1.3/src/glib.mli
archsat.1.1/src/core/ext_logic.ml
archsat.1.1/src/middle/pipe.ml
archsat.1.1/src/core/ext_rewrite.ml
archsat.1.1/src/proof/logic.ml
archsat.1.1/src/main.ml
archsat.1.1/src/proof/term.ml
archsat.1.1/src/util/escape.ml
lemonade.0.6.0/ppx/ppx_lemonade.ml
cordova-plugin-push-notifications.1.1.2/cordova_push.mli
zipperposition.2.1/src/demo/resolution/resolution1.ml
zipperposition.2.1/src/core/Unif_intf.ml
sibylfs-lem.0.4.0/src/typed_ast.ml
cil.1.7.3/src/cil.mli
cil.1.7.3/src/frontc/cabs2cil.ml
cil.1.7.3/src/cil.ml
morbig.0.11.0/src/CST.mli
morbig.0.11.0/src/engine.ml
morbig.0.11.0/src/prelexerState.ml
qcheck-core.0.21.1/src/core/QCheck.mli
beluga.1.0/src/core/context.ml
boomerang.1.1.0/lib/binterp.ml
qcheck.0.21.1/src/core/QCheck.mli
lablgtk.2.18.13/src/glib.mli
ocaml-data-notation.0.0.11/test/data/oasis-examples/PropList.ml
stog_server_multi.0.20.0/lib/tmap.mli
flowtype.0.94.0/src/services/inference/types_js.ml
flowtype.0.94.0/src/typing/env.ml
flowtype.0.94.0/src/common/utils/utils_js.ml
flowtype.0.94.0/src/server/command_handler/commandHandler.ml
flowtype.0.94.0/src/typing/statement.ml
flowtype.0.94.0/src/typing/flow_js.ml
stog_nocaml.0.20.0/lib/tmap.mli
0install.2.18/src/tests/test_sat.ml
lablgtk3-goocanvas2.3.1.3/src/glib.mli
stk.0.1.0/lib/textbuffer.ml
dolmen_model.0.9/src/model/bitv.ml
hdfs.0.4/src/hdfs.mli
hdfs.0.4/src/hdfs.ml
frama-c-base.15.0/src/kernel_services/ast_data/alarms.mli
frama-c-base.15.0/src/kernel_services/plugin_entry_points/db.mli
frama-c-base.15.0/src/kernel_services/ast_data/ast.ml
frama-c-base.15.0/src/libraries/datatype/datatype.ml
frama-c-base.15.0/src/kernel_services/analysis/dataflow2.ml
frama-c-base.15.0/src/kernel_services/abstract_interp/fval.ml
frama-c-base.15.0/src/kernel_services/ast_queries/filecheck.ml
frama-c-base.15.0/src/kernel_services/abstract_interp/offsetmap.ml
frama-c-base.15.0/src/plugins/pdg/build.ml
frama-c-base.15.0/src/kernel_services/ast_queries/cil.ml
frama-c-base.15.0/src/plugins/value/domains/gauges/gauges_domain.ml
oci.0.3/src/Oci_Git.ml
libra-tk.1.1.2/src/idspn/idspn.ml
clangml.4.8.0/clangml/clang__ast.ml
opam-monorepo.0.3.6/duniverse/0install/src/tests/test_sat.ml
zipperposition-tools.2.1/src/demo/resolution/resolution1.ml
zipperposition-tools.2.1/src/core/Unif_intf.ml
rtime.0.9.3/src/rtime.mli
linksem.0.8/papers/oopsla-elf-linking-2016/artefact/linker/lem/src/typed_ast.ml
coqide.8.17.1/kernel/cooking.ml
coqide.8.17.1/kernel/indtypes.ml
coqide.8.17.1/kernel/reduction.ml
coqide.8.17.1/kernel/cClosure.ml
posix-clock.0.4.0-0/src/posix_clock.mli
text-tags.2.5.0/lib/bap_c/bap_c_abi.mli
gopcaml-mode-merlin.0.0.6/gopcaml_state.ml
bap.2.5.0/lib/bap_c/bap_c_abi.mli
0install-gtk.2.18/src/tests/test_sat.ml
menhirSdk.20230608/src/LRijkstraClassic.ml
menhirSdk.20230608/src/LRijkstraFast.ml
batteries.3.6.0/build/myocamlbuild.ml
batteries.3.6.0/examples/benchmark/myocamlbuild.ml
ocamlnet.4.1.9-2/src/netstring/netauth.ml
ocamlnet.4.1.9-2/src/rpc/rpc_proxy.ml
opa-base.1.1.0+4263/compiler/libbsl/bslGeneration.mli
opa-base.1.1.0+4263/compiler/libbsl/bslGeneration.ml
opa-base.1.1.0+4263/compiler/libqmlcompil/qmlTypes.mli
opa-base.1.1.0+4263/compiler/libqmlcompil/typer_w/w_InferErrors.ml
opa-base.1.1.0+4263/compiler/libqmlcompil/typer_w/w_SchemeGenAndInst.mli
opa-base.1.1.0+4263/compiler/libqmlcompil/typer_w/w_Exceptions.ml
opa-base.1.1.0+4263/compiler/libqmlcompil/typer_w/w_SchemeGenAndInst.ml
opa-base.1.1.0+4263/compiler/libqmlcompil/typer_w/w_PublicExport.ml
opa-base.1.1.0+4263/compiler/libqmlcompil/typer_w/w_PrintTypes.ml
opa-base.1.1.0+4263/compiler/libqmlcompil/typer_w/w_ReportErrors.ml
```

**Comment by hhugo** [comment]
Closing. let's move the rest of issues in #2457
